### ISSUE TITLE
Vscode 1.75.1 Stopped working

### ISSUE THREAD

**Issue by Benjapos** [atifkhan161/vs-redoc-viewer#18]
This used to work perfectly, but suddenly stopped.

I have uninstalled all plugins / VSCode (removing the files so it is like a clean installation) still nothing. When I look at task manager, I can see about 10 instances, closing some of them doesn't seem to make any difference, until I stop one with the viewers and it throw an error and i need to restart.

Restarting and trying again also doesn't appear to work. The preview does not display a "cant find page, some kind of error occurred" It is blank like it is processing but not displaying anything.... anyone please please know how i can fix this...?

**Comment by hjoukl** [comment]
Same thing for me, albeit version 1.73.1. Worked beautifully, suddenly stopped working. Reinstall didn't make it work again. 
I haven't tried uninstalling/reinstalling other plugins so far.

I can see this in the OUTPUT -> Log (Extension Host) output:

```
023-03-02 13:14:50.675 [info] ExtensionService#_doActivateExtension Atif.vs-redoc-viewer, startup: false, activationEvent: 'onLanguage:yaml'
2023-03-02 13:15:04.450 [error] RangeError: Maximum call stack size exceeded
    at PreviewServer.startServer (c:\Users\*********\.vscode\extensions\atif.vs-redoc-viewer-0.0.3\out\preview\server.js:45:16)
    at PreviewServer.startServer (c:\Users\*********\.vscode\extensions\atif.vs-redoc-viewer-0.0.3\out\preview\server.js:61:18)
    at PreviewServer.startServer (c:\Users\*********\.vscode\extensions\atif.vs-redoc-viewer-0.0.3\out\preview\server.js:61:18)
    at PreviewServer.startServer (c:\Users\*********\.vscode\extensions\atif.vs-redoc-viewer-0.0.3\out\preview\server.js:61:18)
    at PreviewServer.startServer (c:\Users\*********\.vscode\extensions\atif.vs-redoc-viewer-0.0.3\out\preview\server.js:61:18)
...
```

Best regards, 
Holger
