### ISSUE TITLE
Possible bug: Cannot render split files

### ISSUE THREAD

**Issue by nrail-joerg-walter** [atifkhan161/vs-redoc-viewer#3]
I have a main document and a second common.yaml document. On invocation I get:

```
Something went wrong...
Error parsing http://localhost:9093/common.yaml end of the stream or a document separator is expected at line 16, column 19: margin: 0; ^
Stack trace
SyntaxError: Error parsing http://localhost:9093/common.yaml 
end of the stream or a document separator is expected at line 16, column 19:
                margin: 0;
                      ^
    at Function.syntax (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:63:6628)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:75:36502

YAMLException: end of the stream or a document separator is expected at line 16, column 19:
                margin: 0;
                      ^
    at S (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:122:7371)
    at T (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:122:7469)
    at B (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:122:21177)
    at $ (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:122:21532)
    at W (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:122:21682)
    at Object.e.exports.safeLoad (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:122:22012)
    at Object.parse (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:75:1622)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:122:4942
    at new Promise (<anonymous>)
    at Object.parse (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:122:4847)

ReDoc Version: 2.0.0-rc.28
Commit: 18dbd62
```

When I process the same file with redoc-cli bundle it works fine

**Comment by CesarYapp** [comment]
alguna solución? any solution?
